version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - violetagg
  target-branch: "1.1.x"
  labels:
  - type/dependency-upgrade
  ignore:
  # Don't update Reactor projects
  - dependency-name: io.projectreactor:*
  - dependency-name: io.projectreactor.addons:*
  # Don't update Micrometer
  - dependency-name: io.micrometer:micrometer-bom
    versions:
    - "> 1.14.0"
  # JSR305 backport is fixed to last version with annotations (3.0.1)
  - dependency-name: "com.google.code.findbugs:jsr305"
  # Versions > 6.13 require JDK11+
  - dependency-name: com.diffplug.spotless
    versions:
    - "[6.14.a, 8]"
  # Versions > 4 require JDK11+
  - dependency-name: org.mockito:mockito-core
    versions:
    - "[5.a, 6]"
  # Versions > 6 require JDK17+
  - dependency-name: biz.aQute.bnd.builder
    versions:
    - "[7.a, 8]"
  - dependency-name: org.slf4j:*
    versions:
    - "[2.a, 3]"
  - dependency-name: ch.qos.logback:logback-classic
    versions:
    - "[1.3.a, 1.6]"
  # artifactory: don't upgrade to v5
  - dependency-name: "com.jfrog.artifactory"
    versions:
    - ">= 5.0.a"
  # Versions > 5 require JDK17+
  - dependency-name: org.junit:junit-bom
    versions:
    - "[6.a, 7]"
  # Versions > 0.8 require Gradle 9
  - dependency-name: io.github.reyerizo.gradle.jcstress
    versions:
    - "[0.9.a, 1]"
  rebase-strategy: disabled
- package-ecosystem: github-actions
  directory: "/"
  schedule:
      interval: daily
  open-pull-requests-limit: 10
  assignees:
      - violetagg
  target-branch: "1.1.x"
  labels:
      - type/dependency-upgrade
  rebase-strategy: disabled
